kind: pipeline
name: tahokas-testing 

steps:
  - name: tester
    image: docker 
    commands:
      - docker ps
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
