kind: pipeline
name: tahokas-testing 

steps:
  - name: tester
    image: alpine 
    commands:
      - echo moi > /asd/test
    volumes:
      - name: asd
        path: /asd
  - name: tester2
    image: alpine
    commands:
      - cat /asd/test
    volumes:
      - name: asd
        path: /asd

volumes:
  - name: asd
    temp: {}
